[project]
name = "formal-languages"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.2.5",
    "matplotlib>=3.9.2",
    "networkx>=3.3",
    "notebook>=7.2.2",
    "pydot>=3.0.2",
]
